name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 

      # Install dependencies using pip and pyproject.toml
      - name: Install dependencies
        run: |
          pip install .  # Install from pyproject.toml
      
      # Install coverage
      - name: Install coverage
        run: |
          pip install coverage

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml

      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml  # Path to the coverage report
          token: ${{ secrets.CODECOV_TOKEN }}
