name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-test:
    runs-on: ubuntu-latest  # This uses a GitHub-hosted runner with Ubuntu

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the dependencies listed in requirements.txt
          pip install -e .  # Install the project in editable mode (optional, if needed)

      # Step 4: Run tests using pytest
      - name: Run Python tests with pytest
        run: |
          pytest  # This will run pytest from the root directory, assuming tests are in the 'tests/' folder
