name: Test and Coverage

on:
  push:
    branches:
      - main  # Adjust this if you have a different branch name for main development
  pull_request:
    branches:
      - main  # Trigger for pull requests to main branch

jobs:
  python-test:
    runs-on: ubuntu-latest  # You can change this to windows-latest or macos-latest based on your environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust Python version as needed

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .  # Install your package in editable mode for local testing

      # Run tests with coverage using `coverage run` and generate XML report
      - name: Run tests with coverage
        run: |
          coverage run -m pytest  # Run tests with coverage collection
          coverage xml  # Generate coverage.xml file in XML format

      # Optionally, upload the coverage.xml file as an artifact (for inspection)
      - name: Upload coverage.xml as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml  # Upload the generated coverage.xml file

      # Optional: Display coverage in the GitHub Actions logs
      - name: Display coverage in logs
        run: |
          cat coverage.xml  # Display the contents of coverage.xml in the logs (if desired)
