name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-test:
    runs-on: ubuntu-latest  # You can also use windows-latest if you're on Windows

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify your Python version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install -e .  # Install the local package in editable mode

      # Step 4: Run tests with coverage
      - name: Run tests with coverage
        run: |
          coverage run -m pytest  # Run tests with coverage collection
          coverage xml  # Generate coverage report in XML format

      # Step 5: Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Automatically available GitHub token
          path-to-lcov: coverage.xml  # Path to the coverage report
          format: cobertura  # Specify that the coverage report is in Cobertura format
