name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-test:
    runs-on: ubuntu-latest  # Change to the runner of your choice (e.g., ubuntu-latest, windows-latest)

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install -e .  # Install your package in editable mode

      # Run tests with coverage and generate a report
      - name: Run tests with coverage
        run: |
          pytest --cov=reefcraft --cov-report=xml  # Generate coverage.xml file

      # Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
          path-to-lcov: coverage.xml  # Specify the path to the coverage.xml file
          format: cobertura  # Specify the format as cobertura